### ISSUE TITLE
Logger Initialization issue ->  System.TypeInitializationException: The type initializer for 'Gemstone.Diagnostics.Logger' threw an exception.

### ISSUE THREAD

**Issue by desuryan** [gemstone/phasor-protocols#4]
I am trying to create a sample project by using the library. It shows the below error while I am initializing a new instance of Gemstone.PhasorProtocols.MultiProtocolFrameParser class. The error message is as below.

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gemstone.PhasorProtocols.MultiProtocolFrameParser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Gemstone.Diagnostics.Logger' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Gemstone.Diagnostics.Logger..cctor()
   --- End of inner exception stack trace ---
   at Gemstone.Diagnostics.Logger.AppendStackMessages(String key, String value)
   at Gemstone.PhasorProtocols.MultiProtocolFrameParser..cctor()
   --- End of inner exception stack trace ---
   at Gemstone.PhasorProtocols.MultiProtocolFrameParser..ctor()
   at DeviceToData.Program.Main(String[] args) in C:\Users\20327182\source\repos\pmu-adapter\pmu-adapter\Program.cs:line 15

**Comment by ritchiecarroll** [comment]
The latest NuGet version should reference the diagnostics library properly. These libraries are now being used in production, so I expect they should fine for you now.
